name: alifouadapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  country_flags: ^2.1.1
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_secure_storage: ^9.0.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Alexandria
      fonts:
        - asset: assets/fonts/Alexandria/AlexandriaFLF.ttf
        - asset: assets/fonts/Alexandria/AlexandriaFLF-Bold.ttf
        - asset: assets/fonts/Alexandria/AlexandriaFLF-Italic.ttf

